export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';
export const SUBMIT_SURVEY = 'SUBMIT_SURVEY';
export const SUBMIT_SURVEY_ERROR = 'SUBMIT_SURVEY_ERROR';
export const FETCH_SURVEYS = 'FETCH_SURVEYS';
export const FETCH_SURVEYS_ERROR = 'FETCH_SURVEYS_ERROR';
